project:
  type: website
  output-dir: docs

website:
  title: "Roberto Marino"
  repo-url: "https://github.com/roberto-marino/roberto-marino.github.io"
  site-url: "https://roberto-marino.github.io/"

  navbar:
    left:
      - href: index.qmd
        text: Home
#      - href: about/about.qmd
#        text: About
      - href: papers/papers.qmd
        text: Papers
      - href: teaching/teaching.qmd
        text: Teaching
      - href: theses/theses.qmd
        text: Theses
      - href: activities/activities.qmd
        text: Activities
      - href: projects/projects.qmd
        text: Projects
  page-footer:
    left: "(c) Roberto Marino, 2025-(+inf)"
  twitter-card: true
  open-graph: true
  google-analytics: ""

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc_depth: 3
    toc_float: true
    toc_smooth_scroll: true
    toc_highlight: true
    fig-align: center
    include-in-header:
      text: |
        <script type='application/ld+json'>{"@context":"http://www.schema.org","@type":"person","name":"Roberto Marino","jobTitle":"Research Fellow on Robotics and AI","height":"168 cm","gender":"male","description":"Roberto Marino is a roboticist and computer scientist working at the intersection of AI/ML, control theory and distributed systems. He is currently Post-doc Researcher at University of Messina and he is author of a number of research papers.","url":"roberto-marino.github.io","image":"","address":{"@type":"PostalAddress","addressLocality":"Messina","postalCode":"98123","addressCountry":"Italy"},"alumniOf":[{"@type":"CollegeOrUniversity","name":"Ecole Centrale de Nantes","sameAs":"https://fr.wikipedia.org/wiki/%C3%89cole_centrale_de_Nantes"},{"@type":"CollegeOrUniversity","name":"University of Genova","sameAs":"https://en.wikipedia.org/wiki/Università_di_Genova"}],"worksFor":[{"@type":"Organization","name":"HCLTech"}],"birthDate":"1984-07-15","birthPlace":"Messina, Italy","memberOf":[{"@type":"Organization","name":"IEEE"}],"nationality":[{"@type":"Country","name":"Italy"}]}</script>


