project:
  type: website
  output-dir: docs

website:
  title: "Roberto Marino"
  repo-url: "https://github.com/roberto-marino/roberto-marino.github.io"
  site-url: "https://roberto-marino.github.io/"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about
        text: About
      - href: papers
        text: Papers
      - href: teaching
        text: Teaching
  page-footer:
    left: "(c) Roberto Marino, 2025–. [Disclaimer](disclaimer)"
  twitter-card: true
  open-graph: true
  google-analytics: ""

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



