project:
  type: website

website:
  title: "roberto-marino.github.io"
  repo-url: "https://github.com/roberto-marino/roberto-marino.github.io"
  site-url: "https://roberto-marino.github.io/"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



