---
title: "Roberto Marino, PhD"
about:
    template: trestles
    links:
#        - icon: linkedin
#          text: LinkedIn
#          url: https://www.linkedin.com/in/chrisvoncsefalvay/
#        - icon: twitter
#          text: Twitter
#          url: https://twitter.com/epichrisis
        - icon: github
          text: Github
          url: https://github.com/roberto-marino
#        - icon: instagram
#          text: Instagram
#          url: https://www.instagram.com/chrisvoncsefalvay/
        - text: "{{< fa envelope >}} Email"
          url: mailto:roberto.marino@unime.it
        - text: "{{< ai orcid >}} ORCID 0009-0008-4541-1678"
          url: https://orcid.org/0009-0008-4541-1678
#        - text: "{{< ai google-scholar >}} Google Scholar"
#          url: https://scholar.google.com/citations?user=X_2G-VsAAAAJ
#        - text: "{{< ai viaf >}} VIAF 7190162669581955500004"
#          url: http://viaf.org/viaf/7190162669581955500004
#        - text: "{{< ai isni >}} ISNI 0000 0005 0265 5729"
#          url: https://isni.org/isni/0000000502655729
#        - text: "{{< ai researcherid >}} RID IZD-6900-2023"
#          url: https://www.webofscience.com/wos/author/record/IZD-6900-2023
#        - text: "{{< ai osf >}} OSF"
#          url: https://osf.io/awhgj
image: img/me2.jepg
comments: false
---

*"The miracle is this - the more we share, the more we have" ― Leonard Nimoy*

---

## Bio

I'm a roboticist working at the intersection of AI/ML, control theory and distributed systems.

I attended the [University of Messina](https://www.unime.it) for my undergraduate studies and came back there for my Research Fellowship.

I also hold degrees from [University of Genova](https://www.unige.it) and [Ecole Centrale de Nantes](https://www.ec-nantes.fr) where I studied under an [ERASMUS Mundus scholarship program (EMARO)](https://master-emaro.ec-nantes.fr/) and I completed my PhD.

I'm currently a Research Fellow at [Future Computing Research Laboratory](https://fcrlab.unime.it) of University of Messina under the supervision of [prof. Massimo Villari](https://scholar.google.com/citations?user=LogifUkAAAAJ&hl=it&oi=ao), where I currently follow lines of research about Distributed Learning, Physics-Informed Machine Learning and Clinical Data Modeling.


## Key research interest

* **Robotics and Autonomous Systems:** Aerial Robot Modeling, Data-Driven Control, Lagrangian modeling, DMOC (Discrete Mechanics and Optimal Control)

* **Scientific Machine Learning:** Physics-Informed Neural Network, Neural Stochastic Differential Equations

* **Distributed Learning:** Federated Learning, Multi-Agent Reinforcement Learning


## Personal Life

I am married to Chiara and I am the father of Emma and Agnese. I have a past as a scout educator in AGESCI (Italian Catholic Guides and Scouts Association), and a present as a volunteer with Migrantes, a reality that is all-around involved in the promotion of migrants and refugees in my city.

I love music and studied piano for five years at the Conservatory of Messina. I listen in particular to Jazz music, progressive rock and classical music (with a boundless love for Bach and Debussy).

I love to cook, especially first courses and appetizers, with a preference for traditional Mediterranean dishes.


