---
title: "Teaching"
---

# Reti di Calcolatori e Sistemi Distributi Mod.B

### Anno Accademico 25/26

Il corso, diviso in tre parti, si propone di:

* Parte I: Affrontare le principali problematiche legate alla **programmazione di rete** in linguaggio C utilizzando gli strumenti acquisiti per osservare l'utilizzo dello stack TCP/IP

* Parte II: Introdurre i concetti della **programmazione concorrente** e dei meccanismi di sincronizzazioni offerti dai sistemi *nix

* Parte III: Introdurre le tematiche della **programmazione distributa** attraverso il modello ad Automi a Stati Finiti

|#| Data             | Lezione                          | Materiale                                | Riferimenti   |
|-|------------------|----------------------------------|------------------------------------------|---------------|
|1| 3 Marzo 2026 | Introduzione al corso e Packet Analysis   | [Slides](../documents/labresid_1.pdf), [CS1](../documents/cs1.pdf), [CS2](../documents/cs2.pdf) | Kurose Ch.1, Lordal Ch.1              |
|2| 5 Marzo 2026 | Stack ISO/OSI ed Introduzione ai Socket | [Slides](../documents/labresid_2.pdf), [CS3](../documents/cs3.pdf), [CS4](../documents/cs4.pdf), [CS5](../documents/cs5.pdf), [CS_wf](../documents/cs_wf.pdf) | Lordal Ch.1,2 and Piccardi Ch.13,14 |
|3| 6 Marzo 2026 | Socket Programming in Linux      | [Slides](../documents/labresid_3.pdf), [CS6](../documents/cs_socket.pdf), [<span style="color:#cc0000">HO1</span>](../documents/ho1.pdf), [server_tcp.c](../src/server_tcp.c), [client_tcp.c](../src/client_tcp.c) | Piccardi Ch.13,14 |
|4| 10 Marzo 2026 | TCP Fragmentation | [<span style="color:#cc0000">HO2</span>](../documents/resid26_ho2.pdf) | Piccardi Ch.15 |
|5| 12 Marzo 2026 | Socket Raw di livello 2 | [<span style="color:#cc0000">HO3</span>](../documents/resid26_ho3.pdf), [sniffer_base.c](../src/sniffer_base.c)||
|6| 13 Marzo 2026 | Socket Raw di livello 3 | [<span style="color:#cc0000">HO4</span>](../documents/resid26_ho4.pdf), [ip_sniffer_base.c](../src/ip_sniffer_base.c)||   
|7| 19 Marzo 2026 | I/O Multiplexing con select() | [Slides](../documents/resid26_select.pdf), [<span style="color:#cc0000">HO5</span>](../documents/resid26_ho5.pdf), [server_select.c](https://github.com/roberto-marino/roberto-marino.github.io/blob/main/src/server_select.c), [test_multifd.sh](../src/test_multifd.sh)| Piccardi Ch.10 |
|8| 20 Marzo 2026 | I/O Multiplexing con epoll() | [Slides](../documents/resid26_epoll.pdf), [<span style="color:#cc0000">HO6</span>](../documents/resid26_ho6.pdf), [server_epoll.c](https://github.com/roberto-marino/roberto-marino.github.io/blob/main/src/server_epoll.c), [test_multifd.sh](../src/test_multifd.sh)| Piccardi Ch.10 |
|9| 24 Marzo 2026 | Review and consolidation | | |
|10| 26 Marzo 2026 | Spazi di Indirizzamento IP | [Slides](../documents/resid26_indirizzamento.pdf), [CS_iptools](../documents/cs_iptools.pdf), [CS_ipcalc](../documents/cs_ipcalc.pdf) | |
|11| 27 Marzo 2026 | Socket Multicast | [Slides](../documents/resid26_multicast.pdf), [<span style="color:#cc0000">HO7</span>](../documents/resid26_ho7.pdf), [receiver.c](../src/receiver.c), [sender.c](../src/sender.c) | Piccardi Ch.16, [Link](https://www.cs.emory.edu/~cheung/Courses/558/Syllabus/14-Multicast/intro.html) |
|12| 10 Aprile 2026 | Netlink: Comunicare con il Kernel via Socket | [Slides](../documents/resid26_netlink.pdf), [<span style="color:#cc0000">HO8</span>](../documents/resid26_ho8.pdf), [nl_dummy.c](../src/nl_dummy.c) | |
|13| 14 Aprile 2026 | Virtual Interfaces and Veth-Pair | [Slides](../documents/resid26_vi_veth.pdf), [<span style="color:#cc0000">HO9</span>](../documents/resid26_ho9.pdf), [veth_create_obs.c](../src/veth_create_obs.c) | |
|14| 16 Aprile 2026 | Programming a Container from Scratch | [Slides](../documents/resid26_container.pdf), [<span style="color:#cc0000">HO10</span>](../documents/resid26_ho10.pdf), [container.c](../src/container.c) | |
|15| 17 Aprile 2026 | Routing through namespaces | [<span style="color:#cc0000">HO11</span>](../documents/resid26_ho11.pdf), [topo.c](../src/topo.c) | |
|16| 21 Aprile 2026 | Preprocessing, Compiling, Assembly, Linking | [Slides](../documents/resid26_pcal.pdf), [example.c](../src/example.c), [example.s](../src/example.s)  | <span style="color:#cc0000">No reports needed</span> |
|17| 23 Aprile 2026 | Executable and Linkable Format | [Slides](../documents/resid26_elf.pdf) | <span style="color:#cc0000">No reports needed</span>, CSAPP: Chapter 7 |
: Course Schedule {.striped}

### Prerequisiti
- Programmazione di base in Linguaggio C ([Il linguaggio C, Kernighan & Ritchie](../documents/kr.pdf), [CSAPP: Computer Systems: A Programmer Perspective](../documents/CSAPP_2016.pdf))
- Concetti di Reti di Calcolatori: Tcp/Ip, Routing
- Concetti di Reti di Sistemi Operativi: Scheduling dei processi, Threads, Primitive di sincronizzazione
- Concetti di Algoritmi: Macchine a stati finiti, Complessità Computazionale, Algoritmi su grafi ed alberi

### [Student Reports Tracker](https://docs.google.com/spreadsheets/d/1BKUMWUGtVRyRPycEsoQVzcOsX0i2isjq-T4r1oLNfIU/edit?usp=sharing)

### Modalità d'esame
Report delle esercitazioni + Progetto Finale + Presentazione Orale (<span style="color:#cc0000">con verifica dei concetti e delle abilità acquisite durante le attività di laboratorio</span>)

### Canale Telegram

LabReSiD25-26@unime URL: [t.me/labresid2526](https://t.me/labresid2526)

### Testi Consigliati


1. Ross Kurose, "Reti di Calcolatori ed Internet. Un approccio Top-down" Pearson, 8th edition, [english version on-line](https://www.ucg.ac.me/skladiste/blog_44233/objava_64433/fajlovi/Computer%20Networking%20_%20A%20Top%20Down%20Approach,%207th,%20converted.pdf)

2. Peter L. Lordal, "An Introduction to Computer Networks", [on-line](https://intronetworks.cs.luc.edu/current2/html/index.html)

3. Richard W. Stevens, "UNIX Network Programming", Volume 1, Second Edition: Networking APIs: Sockets and XTI, Prentice Hall

4. Richard W. Stevens, "UNIX Network Programming", Volume 2, Second Edition: Interprocess Communications, Prentice Hall
 
5. Simone Piccardi, "GAPIL: Guida alla programmazione in Linux", [on-line](https://gapil.gnulinux.it/fileshare/gapil.pdf)

6. Achille Pattavina, "Internet e Reti. Fondamenti", Pearson, 3rd edition

7. Andrew S. Tanenbaum, "Sistemi Distribuiti. Principi e paradigmi", Pearson

8. Francesco Bullo, Jorge Cortés, Sonia Martinez, "Distributed Control of Robotic Networks", [on-line](https://fbullo.github.io/dcrn/pdfs/DCRN-BulloCortesMartinez-10mar09.pdf)

9. Robert Love, "Linux Kernel Development", Novell, Second Edition


### Link Utili

1. x86 and amd64 Instruction Reference, [on-line](https://www.felixcloutier.com/x86/)
2. Linux Kernel Source Navigator, [on-line](https://elixir.bootlin.com/linux/v6.13.7/source)

# Computational Modeling for Robotics and Human Computer Interaction

Il corso, teorico/simulativo, della durata di 30 ore (3CFU) affronta le tecniche di modellazione computazionale delle principali tipologie di robot (manipolatori robotici, Robot mobili su ruote e volanti) e gli algoritmi di funzionamento dei visori per realtà immersiva (Kalman, VIO, SLAM). Il corso prevede un test finale di verifica della partecipazione.


# Programma del corso

|#| Data             | Lezione                          | Materiale                                | Riferimenti   |
|-|------------------|----------------------------------|------------------------------------------|---------------|
|1| 18 Marzo 2026 | Introduzione alla robotica, Trasformazioni   | [Slides 0](../documents/rob0.pdf), [Slides 1](../documents/rob1.pdf)  | Khalil, Chapt. 1-2 |
|2| 24 Marzo 2026 | Recap, Rappresentazioni Angolari, Screw Theory   | [Robolib](../documents/robolib.zip), [Notebook ITA/ENG](../documents/NB2.zip)  | Khalil, Chapt. 1-2 |
|3| 1 Aprile 2026 | Direct Geometric Model   | [Slides](../documents/rob3.pdf), [Notebook ITA/ENG](../documents/ur5_intro.zip)  | Khalil, Chapt. 3, [CoppeliaSim](http://www.coppeliarobotics.com) |
|4| 8 Aprile 2026 | Franka Emika Panda Geometric Modelling | [Notebook ITA/ENG](../documents/FrankaEmikaModel.zip) | [Franka Emika Panda Robot](https://franka.de), [Overleaf](https://www.overleaf.com) |
|5| 15 Aprile 2026 | Kinematic and Dynamic model |[Slides](../documents/rob4.pdf) | |
|6| 22 Aprile 2026 | Mobile Robots: Differential Drive | [Slides](../documents/Robotics_Differential_Drive.pdf), [Notebook ITA/ENG](../documents/pioneer_coppelia.zip) | |
: Course Schedule {.striped}    

## Prerequisiti

Sono richiesti **elementi di Algebra Lineare** ed **elementi di programmazione in linguaggio C/Python**.

## Modalità di erogazione

Il corso, teorico/simulativo, prevede **lezioni frontali** ed **esercitazioni simulative al computer**.

## Conseguimento dei crediti formativi

Oltre alla **frequenza obbligatoria**, è previsto un **test finale** per il conseguimento dei CFU.

### Canale Telegram

ComputationalRobotics@Unime URL: [t.me/ComputationalRoboticsUniME](https://t.me/ComputationalRoboticsUniME)


## Bibliografia

*   Wisama Khalil, Etienne Dombre, ”Modeling, Identification and Control of Robots”, Kogan Page Science
*   Siciliano, Sciavicco, Villani, Oriolo, ”Robotica: Modellistica, Pianificazione e Controllo”, McGrawHill
*   Roland Siegwart, Illah Reza Nourbakhsh, Davide Scaramuzza, ”Introduction to Autonomous Mobile Robots”, MIT Press


