---
Title: "Papers"
---

Carnevale, Lorenzo, Antonio Filograna, Francesco Arigliano, Roberto
Marino, Armando Ruggeri, and Maria Fazio. 2023. “Supporting the Natural
Disaster Management Distributing Federated Intelligence over the
Cloud-Edge Continuum: The TEMA Architecture.” In *Proceedings of the
IEEE/ACM 10th International Conference on Big Data Computing,
Applications and Technologies*, 1–6. Taormina (Messina) Italy: ACM.
<https://doi.org/10.1145/3632366.3632371>.

Colosi, Mario, Marco Garofalo, Lorenzo Carnevale, Roberto Marino, Maria
Fazio, and Massimo Villari. 2023. “EDGEmergency: A Cloud-Edge Platform
to Enable Pervasive Computing for Disaster Management.” In *Proceedings
of the IEEE/ACM 10th International Conference on Big Data Computing,
Applications and Technologies*, 1–4. Taormina (Messina) Italy: ACM.
<https://doi.org/10.1145/3632366.3632372>.

Marino, Roberto, Lorenzo Carnevale, Maria Fazio, and Massimo Villari.
2023. “Make Federated Learning a Standard in Robotics by Using ROS2.” In
*Proceedings of the IEEE/ACM 10th International Conference on Big Data
Computing, Applications and Technologies*, 1–6. Taormina (Messina)
Italy: ACM. <https://doi.org/10.1145/3632366.3632373>.

Marino, Roberto, Lorenzo Carnevale, and Massimo Villari. 2023. “When
Robotics Meets Distributed Learning: The Federated Learning Robotic
Network Framework.” In *2023 IEEE Symposium on Computers and
Communications (ISCC)*, 1–6. Gammarth, Tunisia: IEEE.
<https://doi.org/10.1109/ISCC58397.2023.10218022>.

Marino, Roberto, Antonino Marino, Domenica De Domenico, Lorenzo
Carnevale, Mark Adrian Gambito, and Massimo Villari. 2024. “A Low Cost
Platform for Distributed Data-Driven Structural Health Monitoring.” In
*2024 IEEE Symposium on Computers and Communications (ISCC)*, 1–6.
Paris, France: IEEE. <https://doi.org/10.1109/ISCC61673.2024.10733602>.

Marino, Roberto, Antonino Marino, Domenica De Domenico, Lorenzo
Carnevale, and Salvatore Magazù. 2023. “OpenSEM: An Open Framework for
Data-Driven Structural and Environmental Monitoring.” In *Proceedings of
the IEEE/ACM 10th International Conference on Big Data Computing,
Applications and Technologies*, 1–2. Taormina (Messina) Italy: ACM.
<https://doi.org/10.1145/3632366.3632377>.

Marino, Roberto, Fulvio Mastrogiovanni, Antonio Sgorbissa, and Renato
Zaccaria. 2016. “A Minimalistic Quadrotor Navigation Strategy for Indoor
Multi-Floor Scenarios.” In *Intelligent Autonomous Systems 13*, edited
by Emanuele Menegatti, Nathan Michael, Karsten Berns, and Hiroaki
Yamaguchi, 302:1561–70. Cham: Springer International Publishing.
<https://doi.org/10.1007/978-3-319-08338-4_112>.
